title: "Marco's Personal website"
author: "LEONG WENG SAN"
description: "MPU_P2506404"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false             # show article excerpts instead of archive list on the home page
show_frame: true                # display a grey frame on large screens
show_sidebar: false             # show a sidebar instead of the usual header
show_minimal: false             # remove all clutter

#show_frame: "/assets/images/background.svg"

# Menu                          # for available icons see https://fontawesome.com/v5/icons/

navigation:                     # accepts {file, title, url, icon, sidebaricon}
  - {file: "archive.html", title: "Home Page", sidebaricon: home}
  - {file: "README.md", title: "About me", sidebaricon: address-card}

external:                       # accepts {file, title, url, icon, sidebaricon}
  - {title: Mail, icon: envelope, url: "mailto:marcoleong1220@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/marco1220"}
  - {title: Instagram, icon: instagram, url: "https://www.instagram.com/marcoleong122\/"}

comments:
#  disqus_shortname: ""         # see https://disqus.com
#  isso_domain: ""              # see https://isso-comments.de

plugins:
 - jekyll-feed
